// <auto-generated />
namespace SDJ3_3rd_tier.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_required));
        
        string IMigrationMetadata.Id
        {
            get { return "201805120936391_added_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
