// <auto-generated />
namespace SDJ3_3rd_tier.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changed_carId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changed_carId));
        
        string IMigrationMetadata.Id
        {
            get { return "201805141728354_Changed_carId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
